"""
Agricultural Decision Support System — Report Generator
Generates comprehensive agronomic reports covering:
- Farm and Field Profile
- Soil Health Assessment
- Meteorological Impact & Risk Index
- Sugarcane Variety Performance
- AI Yield Prediction & Production Forecast
- Actionable Agronomic Recommendations
"""

import json
from datetime import datetime
from pathlib import Path

class AgronomicReportGenerator:
    def __init__(self, output_dir=None):
        self.output_dir = Path(output_dir) if output_dir else Path(__file__).resolve().parent

    def generate_farm_report(self, farm_data: dict, prediction_data: dict = None, weather_data: dict = None, soil_data: dict = None) -> dict:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        report_id = f"AGR-REP-{int(datetime.now().timestamp())}"

        farm_name = farm_data.get("name", "Demo Sugarcane Farm")
        location = farm_data.get("location", "Kolhapur, Maharashtra")
        area = float(farm_data.get("total_area", farm_data.get("area", 5.0)))

        report = {
            "report_id": report_id,
            "generated_at": timestamp,
            "title": f"Sugarcane Yield & Agricultural Decision Support Report — {farm_name}",
            "farm_overview": {
                "farm_name": farm_name,
                "location": location,
                "address": farm_data.get("address", location),
                "total_area_hectares": area,
                "fields_count": len(farm_data.get("fields", [])) if "fields" in farm_data else 1,
            },
            "meteorological_profile": weather_data or {
                "temperature": "29.0°C",
                "rainfall": "1200 mm/year",
                "humidity": "72%",
                "weather_risk": "Low",
                "climate_suitability": "Optimal"
            },
            "soil_profile": soil_data or {
                "soil_type": "Black Cotton Soil",
                "soil_ph": 6.8,
                "soil_moisture": "65%",
                "health_score": "95/100",
                "suitability": "Highly Suitable"
            },
            "yield_forecast": prediction_data or {
                "variety": "Co 86032",
                "predicted_yield_tha": 72.4,
                "expected_production_tonnes": round(72.4 * area, 1),
                "confidence": "91.3%",
                "risk_category": "Low",
                "crop_health_status": "Healthy"
            },
            "key_recommendations": [
                "Maintain scheduled furrow irrigation during Grand Growth elongation phase.",
                "Ensure nitrogen top-dressing is completed before 120 days post-planting.",
                "Inspect field drainage channels to prevent localized water stagnation during heavy showers.",
                "Schedule harvesting when cane brix reaches 18-20% to maximize sugar recovery."
            ],
            "disclaimer": "This advisory report is generated by AI-Based Sugarcane Yield Forecasting & Decision Support System. Verify critical interventions with local agricultural extension officers."
        }

        # Save JSON artifact
        json_path = self.output_dir / f"{report_id}.json"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2)

        return report
