import React, { useState, useEffect } from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine, Legend } from 'recharts';
import AppLayout from '../components/AppLayout';
import { mlApi, predictionApi } from '../services/api';
import toast, { Toaster } from 'react-hot-toast';

const SCENARIOS = [
  { label: 'Normal Conditions',     changes: {} },
  { label: 'Increased Rainfall',    changes: { rainfall_mm: 1400 } },
  { label: 'Reduced Rainfall',      changes: { rainfall_mm: 600  } },
  { label: 'High Soil Moisture',    changes: { soil_moisture: 75 } },
  { label: 'Low Soil Moisture',     changes: { soil_moisture: 35 } },
  { label: 'Higher Temperature',    changes: { temperature_c: 38 } },
  { label: 'Optimal Temperature',   changes: { temperature_c: 30 } },
  { label: 'High Nitrogen',         changes: { soil_nitrogen: 250 } },
  { label: 'Low Nitrogen',          changes: { soil_nitrogen: 80  } },
];

export default function SimulatorPage() {
  const [base, setBase] = useState({ rainfall_mm:1200, temperature_c:28, humidity:65, soil_moisture:62, soil_ph:6.8, soil_nitrogen:150, soil_phosphorus:60, soil_potassium:80, area_hectare:5, variety:'Co 86032', state:'Maharashtra', season:'Kharif' });
  const [currentPred, setCurrentPred]   = useState(80);
  const [result, setResult]             = useState(null);
  const [batchResults, setBatchResults] = useState([]);
  const [loading, setLoading]           = useState(false);
  const [batchLoading, setBatchLoading] = useState(false);
  const [lastPred, setLastPred]         = useState(null);

  useEffect(() => {
    predictionApi.list().then(r => {
      const p = r.data?.predictions?.[0];
      if (p) {
        setLastPred(p);
        setCurrentPred(Number(p.predicted_yield));
        setBase(b => ({ ...b, rainfall_mm: Number(p.rainfall)||1200, temperature_c: Number(p.temperature)||28, humidity: Number(p.humidity)||65, soil_moisture: Number(p.soil_moisture)||62, soil_ph: Number(p.soil_ph)||6.8, variety: p.variety||'Co 86032', area_hectare: Number(p.area)||5 }));
      }
    }).catch(() => {});
  }, []);

  const [custom, setCustom] = useState({});

  const runSingle = async () => {
    if (!Object.keys(custom).length) return toast.error('Modify at least one parameter in the Custom Scenario.');
    setLoading(true);
    try {
      const r = await mlApi.whatIf({ base, scenario: custom, current_prediction: currentPred });
      setResult(r.data);
    } catch (e) { toast.error(e.message); }
    finally { setLoading(false); }
  };

  const runBatch = async () => {
    setBatchLoading(true);
    try {
      const results = await Promise.all(
        SCENARIOS.map(s => mlApi.whatIf({ base, scenario: s.changes, current_prediction: currentPred })
          .then(r => ({ label: s.label, ...r.data })).catch(() => null))
      );
      setBatchResults(results.filter(Boolean));
    } catch (e) { toast.error(e.message); }
    finally { setBatchLoading(false); }
  };

  const chartData = batchResults.map(r => ({
    name: r.label.replace(' Conditions','').replace(' Rainfall','↑/↓').slice(0,18),
    yield: r.scenario_prediction,
    diff:  r.difference,
  }));

  return (
    <AppLayout>
      <Toaster position="top-right" />
      <div className="page-container">
        <div className="page-header">
          <div>
            <p className="eyebrow">What-If Analysis</p>
            <h1 className="page-title">Yield Scenario Simulator</h1>
            <p className="page-subtitle">Explore how changes in conditions affect predicted yield. These are <strong>model-based estimates</strong>, not guaranteed outcomes.</p>
          </div>
        </div>

        <div className="sim-disclaimer">
          ⚠️ <strong>Model-Based Estimates Only:</strong> Scenario results are generated by the ML model using input sensitivity analysis. They do not replace agronomic expertise or real-world observation.
        </div>

        <div className="dash-two-col">
          {/* Base conditions */}
          <div className="dash-panel">
            <div className="dash-panel-header">
              <h3>Base Conditions</h3>
              {lastPred && <span className="badge badge-green">From Latest Prediction</span>}
            </div>
            <div className="sim-form-grid">
              {[
                { key:'rainfall_mm',    label:'Rainfall (mm)',    min:0,   max:3000, step:50  },
                { key:'temperature_c',  label:'Temperature (°C)', min:10,  max:50,   step:0.5 },
                { key:'humidity',       label:'Humidity (%)',     min:0,   max:100,  step:1   },
                { key:'soil_moisture',  label:'Soil Moisture (%)',min:0,   max:100,  step:1   },
                { key:'soil_ph',        label:'Soil pH',          min:4,   max:10,   step:0.1 },
                { key:'soil_nitrogen',  label:'Nitrogen (kg/ha)', min:0,   max:400,  step:10  },
              ].map(f => (
                <div key={f.key} className="sim-field">
                  <label>{f.label}</label>
                  <div className="sim-range-wrap">
                    <input type="range" min={f.min} max={f.max} step={f.step}
                      value={base[f.key]} onChange={e => setBase(b => ({...b, [f.key]: Number(e.target.value)}))} />
                    <span className="sim-range-val">{Number(base[f.key]).toFixed(f.step < 1 ? 1 : 0)}</span>
                  </div>
                </div>
              ))}
            </div>
            <div className="sim-base-pred">
              Current Prediction: <strong>{currentPred.toFixed(1)} t/ha</strong>
              {lastPred && <span style={{fontSize:12,color:'#9ca3af',marginLeft:8}}>(from {lastPred.variety})</span>}
            </div>
          </div>

          {/* Custom scenario */}
          <div className="dash-panel">
            <div className="dash-panel-header"><h3>Custom Scenario</h3><span className="badge badge-purple">Modify to compare</span></div>
            <div className="sim-form-grid">
              {[
                { key:'rainfall_mm',    label:'Rainfall (mm)',    min:0,  max:3000, step:50  },
                { key:'temperature_c',  label:'Temperature (°C)', min:10, max:50,   step:0.5 },
                { key:'soil_moisture',  label:'Soil Moisture (%)',min:0,  max:100,  step:1   },
                { key:'soil_nitrogen',  label:'Nitrogen (kg/ha)', min:0,  max:400,  step:10  },
              ].map(f => (
                <div key={f.key} className="sim-field">
                  <label>{f.label}</label>
                  <div className="sim-range-wrap">
                    <input type="range" min={f.min} max={f.max} step={f.step}
                      value={custom[f.key] ?? base[f.key]}
                      onChange={e => setCustom(c => ({...c, [f.key]: Number(e.target.value)}))} />
                    <span className="sim-range-val">{Number(custom[f.key] ?? base[f.key]).toFixed(f.step<1?1:0)}</span>
                  </div>
                </div>
              ))}
            </div>
            <button className="btn-primary" onClick={runSingle} disabled={loading} style={{marginTop:12,width:'100%'}}>
              {loading ? '🔄 Simulating…' : '🔮 Run Custom Scenario'}
            </button>

            {result && (
              <div className={`sim-result ${result.difference >= 0 ? 'sim-result-pos' : 'sim-result-neg'}`}>
                <div className="sir-row">
                  <span>Current</span><strong>{result.base_prediction?.toFixed(1)} t/ha</strong>
                </div>
                <div className="sir-row">
                  <span>Scenario</span><strong>{result.scenario_prediction?.toFixed(1)} t/ha</strong>
                </div>
                <div className="sir-diff">
                  {result.difference >= 0 ? '▲' : '▼'} {Math.abs(result.difference).toFixed(1)} t/ha ({result.percentage_change >= 0 ? '+' : ''}{result.percentage_change?.toFixed(1)}%)
                </div>
                {result.changed_features?.map((f, i) => (
                  <div key={i} className="sir-feature">
                    <span>{f.feature}:</span> <span>{f.from} → {f.to}</span>
                    <span className={f.impact === 'positive' ? 'td-green' : 'sim-neg'}>{f.impact}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Batch scenarios */}
        <div className="dash-panel">
          <div className="dash-panel-header">
            <h3>Pre-defined Scenario Comparison</h3>
            <button className="btn-primary" onClick={runBatch} disabled={batchLoading}>
              {batchLoading ? '🔄 Running…' : '▶ Run All Scenarios'}
            </button>
          </div>
          <div className="scenarios-list">
            {SCENARIOS.map(s => (
              <div key={s.label} className="scenario-pill">
                <span>{s.label}</span>
                {Object.entries(s.changes).map(([k,v]) => <span key={k} className="sc-change-tag">{k.replace(/_/g,' ')}: {v}</span>)}
              </div>
            ))}
          </div>

          {batchResults.length > 0 && (
            <>
              <ResponsiveContainer width="100%" height={260}>
                <BarChart data={chartData} margin={{ top:16, right:8, bottom:24, left:-10 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                  <XAxis dataKey="name" tick={{ fontSize: 10 }} angle={-25} textAnchor="end" interval={0} />
                  <YAxis tick={{ fontSize: 11 }} unit="t/ha" />
                  <Tooltip formatter={(v, n) => [n==='yield' ? `${v.toFixed(1)} t/ha` : `${v>=0?'+':''}${v.toFixed(1)} t/ha`, n==='yield'?'Yield':'Difference']} />
                  <Legend />
                  <ReferenceLine y={currentPred} stroke="#94a3b8" strokeDasharray="4 4" label={{ value:'Baseline', fontSize:11 }} />
                  <Bar dataKey="yield" name="Scenario Yield" radius={[4,4,0,0]}>
                    {chartData.map((d, i) => <Cell key={i} fill={d.diff >= 0 ? '#16a34a' : '#ef4444'} />)}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>

              <div className="table-wrap" style={{ marginTop: 16 }}>
                <table className="data-table">
                  <thead><tr><th>Scenario</th><th>Predicted Yield</th><th>Difference</th><th>Change %</th></tr></thead>
                  <tbody>
                    {batchResults.map(r => (
                      <tr key={r.label}>
                        <td className="td-bold">{r.label}</td>
                        <td className={r.scenario_prediction >= currentPred ? 'td-green' : ''}>{r.scenario_prediction?.toFixed(1)} t/ha</td>
                        <td style={{ color: r.difference >= 0 ? '#16a34a' : '#ef4444' }}>{r.difference >= 0 ? '+' : ''}{r.difference?.toFixed(1)} t/ha</td>
                        <td style={{ color: r.percentage_change >= 0 ? '#16a34a' : '#ef4444' }}>{r.percentage_change >= 0 ? '+' : ''}{r.percentage_change?.toFixed(1)}%</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </>
          )}
        </div>
      </div>
    </AppLayout>
  );
}
